server:
  port: 8088
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/st-test
    username: postgres
    password: pgsql
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      connection-timeout: 60000
      validation-timeout: 10000
  jpa:
    show-sql: true
#  redis:
#    host: 127.0.0.1
#    database: 0
#    port: 6379
#    password:
#    lettuce:
#      pool:
#        max-active: 10
#        max-idle: 10
#        max-wait: 5ms
#tb:
#  url: https://nybx-ljyz.cpic.com.cn/aims

logging:
  level: debug
  level.top: debug